"use client"
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { usePathname } from "next/navigation";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathNmae = usePathname();
  // console.log(pathNmae);
  
  
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-gray-600 to-black " /*className={inter.className}*/>
      <ToastContainer />
          {
            pathNmae !== "/editorworkspace" && !pathNmae.startsWith("/subadmindashboard")?<Navbar />:null
          }   
          {children}
        </body>
    </html>
  );
}
